export const data = [
  {
    id: 1,
    title: "Патруль - Кто уважаемый! Меня никто не уважает! (Терпила – часть первая)",
    channel: "https://yt3.googleusercontent.com/0Jk25mOKLGqBclKPtqy-OTOOT-0I1Uwtam3JmCuUVrIYDpxCO-xQBRSC3S9U6YneOrqXfG4yww=s900-c-k-c0x00ffffff-no-rj",
    channelName: 'NTK TV',
    img: "https://i.ytimg.com/vi/utuRmwXpygQ/hqdefault.jpg",
    views: "2 млн просмотров",
    publishedAt: "5 лет назад",
    duration: "2:35",
  },
  {
    id: 2,
    title: "Патруль - Кто уважаемый! Меня никто не уважает! (Терпила – часть третья)",
    channel: "https://yt3.googleusercontent.com/0Jk25mOKLGqBclKPtqy-OTOOT-0I1Uwtam3JmCuUVrIYDpxCO-xQBRSC3S9U6YneOrqXfG4yww=s900-c-k-c0x00ffffff-no-rj",
    channelName: 'NTK TV',
    img: "https://i.ytimg.com/vi/8kprkrsNkRM/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCp33X6oMXnN7yySDwlFtMSLL1RLA",
    views: "3,3 млн просмотров",
    publishedAt: "5 лет назад",
    duration: "3:23",
  },
  {
    id: 3,
    title: "Патруль - новое начальство (Первая часть)",
    channel: "https://yt3.googleusercontent.com/0Jk25mOKLGqBclKPtqy-OTOOT-0I1Uwtam3JmCuUVrIYDpxCO-xQBRSC3S9U6YneOrqXfG4yww=s900-c-k-c0x00ffffff-no-rj",
    channelName: 'NTK TV',
    img: "https://i.ytimg.com/vi/94gsfYyYEmI/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBcXYgjITcEXmLMh4Ng4AD__wL4fw",
    views: "3,8 млн просмотров",
    publishedAt: "5 лет назад",
    duration: "4:52",
  },
  {
    id: 4,
    title: "Патруль - новое начальство (Вторая часть)",
    channel: "https://yt3.googleusercontent.com/0Jk25mOKLGqBclKPtqy-OTOOT-0I1Uwtam3JmCuUVrIYDpxCO-xQBRSC3S9U6YneOrqXfG4yww=s900-c-k-c0x00ffffff-no-rj",
    channelName: 'NTK TV',
    img: "https://i.ytimg.com/vi/9aIt4nDQ1Xo/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDpvM_k3h5fFzc4eEkrGsDUg5IRLg",
    views: "3 млн просмотров",
    publishedAt: "3 лет назад",
    duration: "5:07",
  },
  {
    id: 5,
    title: "Патруль - Кто уважаемый! Меня никто не уважает! (Терпила – часть вторая)",
    channel: "https://yt3.googleusercontent.com/0Jk25mOKLGqBclKPtqy-OTOOT-0I1Uwtam3JmCuUVrIYDpxCO-xQBRSC3S9U6YneOrqXfG4yww=s900-c-k-c0x00ffffff-no-rj",
    channelName: 'NTK TV',
    img: "https://i.ytimg.com/vi/2Zl-wXiqGQk/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLD9ElxnAC0W_v90LkzW-ESjzi6liw",
    views: "2 млн просмотров",
    publishedAt: "5 лет назад",
    duration: "3:17",
  }
];
