name: YouTube Clone CI/CD

on:
  push:
    branches:
      ["main", "dev", "Erjan", "Muhammed", "Almir", "Miras", "Nurbai", "dony"]
  pull_request:
    branches:
      ["main", "dev", "Erjan", "Muhammed", "Almir", "Miras", "Nurbai", "dony"]

jobs:
  compatibility-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6.0.2

      - name: Set up Latest Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "latest"
          check-latest: true
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint & Build Check
        run: npm run ready
